###############################################
# COMPLETE JSSP CONFIGURATION FILE (YAML)     #
###############################################
# You can comment parameters and adjust values.

# Algorithm to run: tabu | sa | both
# Neighborhood comparison mode: 'sa_compare' or 'tabu_compare'
# algo: sa_compare
# Default currently set to TABU.
algo: tabu_compare
# algo: sa_compare


# Path to a single instance file or a directory with multiple instances.
instance: data/JSPLIB/instances/ta80

# Number of independent runs (for each algorithm if 'both').
runs: 1

# RNG seed (affects stochastic parts; starting permutation is deterministic sequential).
seed: 7

# Time limit (ms) for a single algorithm run; null = no limit.
time_limit_ms: null


#############################
# TABU SEARCH PARAMETERS    #
#############################
tabu:
  # Maximum number of iterations.
  iterations: 1000   # More iterations can help escape stagnation.
  # Tabu tenure (iterations a move stays forbidden).
  tenure: 15        # ~sqrt(number of operations); try 12–18.
  # Neighborhood type: swap_adjacent_neighborhood | fibonachi_neighborhood
  # neighborhood: swap_adjacent_neighborhood
  neighborhood: fibonachi_neighborhood
  # Enable diversification (stagnation-triggered random perturbations + tenure lift)
  enable_diversification: true

#############################
# SIMULATED ANNEALING PARAMETERS
#############################
sa:
  # Quick variant for tests (reduced vs earlier examples)
  iterations: 1000       
  initial_temp: 50.0   
  cooling: 0.90        
  neighbor_moves: 1     

  # neighborhood: swap_adjacent_neighborhood
  neighborhood: fibonachi_neighborhood
  
#############################
# CHARTS / OUTPUT            #
#############################
charts:
  # Base directory for artifacts (cleaned of files before run).
  dir: charts_cfg
  # Simplified: all plots and traces are generated automatically.
  # Generate per-iteration Gantt charts (can be large & slow). Set false to disable.
  iter_gantts: false
