name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,viz]

      - name: Black (check)
        run: |
          python -m black --check .

      - name: isort (check)
        run: |
          python -m isort --check-only --diff src tests

      - name: flake8
        run: |
          python -m flake8 src tests

      - name: Ruff (lint)
        run: |
          python -m ruff check .

      - name: mypy
        run: |
          python -m mypy src tests

      - name: Pytest
        run: |
          python -m pytest

      - name: Upload test artifacts (JSON charts) if present
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: |
            charts/**/*.json
            charts/**/*.png
          if-no-files-found: ignore
